env: standard
runtime: nodejs16
service: default
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  DATABASE_USER: $DATABASE_USER
  DATABASE_PASS: $DATABASE_PASS
  DATABASE_NAME: $DATABASE_NAME
  GCSQL_CONNECTION_NAME: $GCSQL_CONNECTION_NAME
  DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASS}@localhost/${DATABASE_NAME}?host=/cloudsql/${GCSQL_CONNECTION_NAME}
