version: "3.8"
services:
  db:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal-site-db
    ports:
      - "6543:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
