export DATABASE_USER=$DATABASE_URL
export DATABASE_PASS=$DATABASE_PASS
export DATABASE_NAME=$DATABASE_NAME
export DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@localhost/${DATABASE_NAME}
export GCSQL_CONNECTION_NAME=$GCSQL_CONNECTION_NAME