name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1

      - name: Install modules
        run: yarn

      - name: Run linter
        run: yarn lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1

      - name: Install modules
        run: yarn

      - name: Substitute environment variables for App Engine and Cloud Build
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          GCSQL_CONNECTION_NAME: ${{ secrets.GCSQL_CONNECTION_NAME }}
        run: |
          envsubst < app.yaml > tmp.yaml && mv tmp.yaml app.yaml
          envsubst < deploy/env.sh > tmp.yaml && mv tmp.yaml deploy/env.sh

      - id: "auth"
        name: Set up authentication
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google App Engine
        run: gcloud app deploy --quiet
